/*CREACIÓN DE LA BD*/
DROP DATABASE IF EXISTS bd_tema5;
CREATE DATABASE bd_tema5 CHARACTER SET utf8mb4 COLLATE 'utf8mb4_spanish_ci';
USE bd_tema5;

/*CREACIÓN DE LAS TABLAS*/
  CREATE TABLE ALUMNOS (DNI VARCHAR(10), APENOM VARCHAR(30), DIREC VARCHAR(30), POBLA VARCHAR(15), TELEF VARCHAR(10));
  CREATE TABLE ALUM1213 (DNI VARCHAR(10), NOMBRE VARCHAR(15), APELLIDOS VARCHAR(20), FECHA_NAC DATETIME, DIRECCION VARCHAR(20), POBLACION VARCHAR(20), PROVINCIA VARCHAR(20), CURSO TINYINT, NIVEL VARCHAR(10), CLASE CHAR(1), FALTAS1 TINYINT, FALTAS2 TINYINT, FALTAS3 TINYINT);
  CREATE TABLE ASIGNATURAS (COD TINYINT, NOMBRE VARCHAR(25));
  CREATE TABLE DEPART (DEPT_NO TINYINT, DNOMBRE VARCHAR(14), LOC VARCHAR(14));
  CREATE TABLE EMPLE (EMP_NO SMALLINT, APELLIDO VARCHAR(10), OFICIO VARCHAR(10), DIR SMALLINT, FECHA_ALT DATETIME, SALARIO INT, COMISION INT, DEPT_NO TINYINT);
  CREATE TABLE LECTOR (NUMLECTOR INT, NOMLECTOR VARCHAR(30), TIPOLECTOR INT);
  CREATE TABLE LIBRERIA (TEMA VARCHAR(15), ESTANTE CHAR(1), EJEMPLARES TINYINT);
  CREATE TABLE LIBRO (CODLIBRO INT, TITULO VARCHAR(30), NUMPAG SMALLINT, EDITORIAL VARCHAR(20), AUTOR VARCHAR(30));
  CREATE TABLE NOTAS (DNI VARCHAR(10), COD TINYINT, NOTA TINYINT);
  CREATE TABLE NOTAS_ALUMNOS (NOMBRE_ALUMNO VARCHAR(25), NOTA1 TINYINT, NOTA2 TINYINT, NOTA3 TINYINT);
  CREATE TABLE PRESTAMO (CODLIBRO INT, NUMLECTOR INT, FPRESTA DATETIME, DIAS DOUBLE);

/*INSERCIÓN DE DATOS*/
-- INSERTING into ALUMNOS
Insert into ALUMNOS (DNI,APENOM,DIREC,POBLA,TELEF) values ('16344345','Alcalde García, Elena','C/Las Matas, 24','Madrid','917766545');
Insert into ALUMNOS (DNI,APENOM,DIREC,POBLA,TELEF) values ('16448242','Cerrato Vela, Luis','C/Mina 28 - 3A','Madrid','916566545');
Insert into ALUMNOS (DNI,APENOM,DIREC,POBLA,TELEF) values ('16882942','Díaz Fernández, María','C/Luis Vives 25','Móstoles','915577545');
-- INSERTING into ALUM1213
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('34448974N','CONCHA','ESTRUCH VIDAL',str_to_date('10/11/1985','%d/%m/%Y'),'C/ MEDICO FELIX, 12','BERROCALEJO','CACERES',2,'DAM','D',0,0,0);
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('34448999N','DORA','MARTIN BREÑA',str_to_date('10/11/1994','%d/%m/%Y'),'C/ MEDICO FELIX, 10','CACERES','CACERES',1,'ASIR','D',0,0,0);
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('16562562W','Eduardo','Bravo López',str_to_date('02/02/1989','%d/%m/%Y'),'C/ Clavijo, 40','Logroño','La Rioja',2,'DAM','D',5,2,3);
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('16654654A','Luis Javier','Martínez Lajo',str_to_date('03/03/1993','%d/%m/%Y'),'C/ Bretón, 14','Logroño','La Rioja',2,'DAM','D',1,0,1);
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('16432432J','Ana','Martínez Escobés',str_to_date('03/04/1994','%d/%m/%Y'),'C/ Madrid, 12','Lardero','La Rioja',1,'ASIR','V',3,8,1);
Insert into ALUM1213 (DNI,NOMBRE,APELLIDOS,FECHA_NAC,DIRECCION,POBLACION,PROVINCIA,CURSO,NIVEL,CLASE,FALTAS1,FALTAS2,FALTAS3) values ('16789789A','Eduardo','Castor Flores',str_to_date('08/10/1989','%d/%m/%Y'),'C/ Los almendros, 4','Villamediana','La Rioja',1,'DAM','D',0,0,0);
-- INSERTING into ASIGNATURAS
Insert into ASIGNATURAS (COD,NOMBRE) values (1,'Programación');
Insert into ASIGNATURAS (COD,NOMBRE) values (2,'Sist. Informáticos');
Insert into ASIGNATURAS (COD,NOMBRE) values (3,'Bases de datos');
Insert into ASIGNATURAS (COD,NOMBRE) values (4,'FOL');
Insert into ASIGNATURAS (COD,NOMBRE) values (5,'Inglés técnico');
Insert into ASIGNATURAS (COD,NOMBRE) values (6,'Lenguajes de marcas');
Insert into ASIGNATURAS (COD,NOMBRE) values (7,'Seguridad');
Insert into ASIGNATURAS (COD,NOMBRE) values (8,'Entornos');
-- INSERTING into DEPART
Insert into DEPART (DEPT_NO,DNOMBRE,LOC) values (10,'CONTABILIDAD','SEVILLA');
Insert into DEPART (DEPT_NO,DNOMBRE,LOC) values (20,'INVESTIGACION','MADRID');
Insert into DEPART (DEPT_NO,DNOMBRE,LOC) values (30,'VENTAS','BARCELONA');
Insert into DEPART (DEPT_NO,DNOMBRE,LOC) values (40,'PRODUCCION','BILBAO');
-- INSERTING into EMPLE
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7369,'SANCHEZ','EMPLEADO',7902,str_to_date('17/12/1990','%d/%m/%Y'),1040,null,20);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7499,'ARROYO','VENDEDOR',7698,str_to_date('20/02/1990','%d/%m/%Y'),1500,390,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7521,'SALA','VENDEDOR',7698,str_to_date('22/02/1991','%d/%m/%Y'),1625,650,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7566,'JIMENEZ','DIRECTOR',7839,str_to_date('02/04/1991','%d/%m/%Y'),2900,null,20);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7654,'MARTIN','VENDEDOR',7698,str_to_date('29/09/1991','%d/%m/%Y'),1600,1020,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7698,'NEGRO','DIRECTOR',7839,str_to_date('01/05/1991','%d/%m/%Y'),3005,null,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7782,'CEREZO','DIRECTOR',7839,str_to_date('09/06/1991','%d/%m/%Y'),2885,null,10);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7788,'GIL','ANALISTA',7566,str_to_date('09/11/1991','%d/%m/%Y'),3000,null,20);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7839,'REY','PRESIDENTE',null,str_to_date('17/11/1991','%d/%m/%Y'),4100,null,10);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7844,'TOVAR','VENDEDOR',7698,str_to_date('08/09/1991','%d/%m/%Y'),1350,0,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7876,'ALONSO','EMPLEADO',7788,str_to_date('23/09/1991','%d/%m/%Y'),1430,null,20);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7900,'JIMENO','EMPLEADO',7698,str_to_date('03/12/1991','%d/%m/%Y'),1335,null,30);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7902,'FERNANDEZ','ANALISTA',7566,str_to_date('03/12/1991','%d/%m/%Y'),3000,null,20);
Insert into EMPLE (EMP_NO,APELLIDO,OFICIO,DIR,FECHA_ALT,SALARIO,COMISION,DEPT_NO) values (7934,'MUÑOZ','EMPLEADO',7782,str_to_date('23/01/1992','%d/%m/%Y'),1690,null,10);
-- INSERTING into LECTOR
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (1,'Posadas Gil, Inés',3);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (2,'Sánchez Pons, José',3);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (3,'Gómez Sáez, Miguel',3);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (10,'Santana Pérez, Eva',4);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (11,'Betancor Díaz, Yolanda',4);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (20,'Blasco Ulla, Juan Luis',1);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (22,'Marín Gómez, Ana',1);
Insert into LECTOR (NUMLECTOR,NOMLECTOR,TIPOLECTOR) values (30,'Plaza Ortiz, Juan',8);
-- INSERTING into LIBRERIA
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('INFORMATICA','A',15);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('ECONOMIA','A',10);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('DEPORTES','B',8);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('FILOSOFIA','C',7);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('DIBUJO','C',10);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('MEDICINA','C',16);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('BIOLOGIA','A',11);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('GEOLOGIA','D',7);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('SOCIEDAD','D',9);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('LABORES','B',20);
Insert into LIBRERIA (TEMA,ESTANTE,EJEMPLARES) values ('JARDINERIA','E',6);
-- INSERTING into LIBRO
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (12,'Don Quijote I',517,'Anaya','Cervantes');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (13,'Don Quijote II',611,'Anaya','Cervantes');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (20,'El principito',120,'Andina','Saint_Exupery');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (35,'Fortunata y Jacinta',625,'PlazaJanes','Pérez-Galdós');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (40,'Caperucuta en Manhattan',310,'Salamandra','Martín GAite');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (41,'La piel del tambor',280,'Circulo','Pérez-Reverte');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (42,'Afrodita',421,'Espasa','Isabel Allende');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (50,'Viajar',675,'BBVA',null);
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (51,'España en sus caminos',534,'BBVA',null);
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (52,'Aeroguía del litoral',340,'Planeta',null);
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (65,'Don Quijote I',578,'Planeta','Cervantes');
Insert into LIBRO (CODLIBRO,TITULO,NUMPAG,EDITORIAL,AUTOR) values (66,'Don Quijote II',600,'Planeta','Cervantes');
-- INSERTING into NOTAS
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',1,6);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',2,5);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',3,6);
Insert into NOTAS (DNI,COD,NOTA) values ('16448242',4,6);
Insert into NOTAS (DNI,COD,NOTA) values ('16448242',5,8);
Insert into NOTAS (DNI,COD,NOTA) values ('16448242',6,4);
Insert into NOTAS (DNI,COD,NOTA) values ('16448242',7,5);
Insert into NOTAS (DNI,COD,NOTA) values ('16882942',4,8);
Insert into NOTAS (DNI,COD,NOTA) values ('16882942',5,7);
Insert into NOTAS (DNI,COD,NOTA) values ('16882942',6,8);
Insert into NOTAS (DNI,COD,NOTA) values ('16882942',7,9);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',4,5);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',5,6);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',6,8);
Insert into NOTAS (DNI,COD,NOTA) values ('16344345',7,4);
-- INSERTING into NOTAS_ALUMNOS
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Alcalde García, M. Luisa',5,5,5);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Benito Martín, Luis',7,6,8);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Casas Martínez, Manuel',7,5,5);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Casas Sánchez, Ana',6,9,8);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Díaz Sánchez, Maria',null,null,7);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Martín Salas, Fernando',6,5,7);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Sánchez Fuentes, Susana',4,5,4);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Jover Sánchez, Mario',7,7,5);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Lafuente Sánchez, Sara',6,6,6);
Insert into NOTAS_ALUMNOS (NOMBRE_ALUMNO,NOTA1,NOTA2,NOTA3) values ('Sánchez Lahera, Fernando',3,3,6);
-- INSERTING into PRESTAMO
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (20,11,str_to_date('01/06/2012','%d/%m/%Y'),4);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (50,20,str_to_date('05/03/2012','%d/%m/%Y'),92);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (51,20,str_to_date('06/05/2012','%d/%m/%Y'),30);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (52,22,str_to_date('06/05/2012','%d/%m/%Y'),30);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (12,20,str_to_date('12/04/2012','%d/%m/%Y'),54);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (13,11,str_to_date('10/05/2012','%d/%m/%Y'),26);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (40,3,str_to_date('01/11/2011','%d/%m/%Y'),217);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (42,30,str_to_date('05/05/2012','%d/%m/%Y'),31);
Insert into PRESTAMO (CODLIBRO,NUMLECTOR,FPRESTA,DIAS) values (35,1,str_to_date('15/04/2012','%d/%m/%Y'),51);

/*CREACIÓN DE ÍNDICES Y CLAVES*/
CREATE UNIQUE INDEX ALUM_PK_DNI ON ALUM1213 (DNI);
CREATE UNIQUE INDEX ALU_PK_DNI ON ALUMNOS (DNI);
CREATE UNIQUE INDEX ASI_PK_CO ON ASIGNATURAS (COD);
CREATE UNIQUE INDEX DEP_PK_DE ON DEPART (DEPT_NO);
CREATE UNIQUE INDEX EMP_PK_EM ON EMPLE (EMP_NO);
CREATE UNIQUE INDEX NOT_PK_DNICOD ON NOTAS (DNI, COD);
CREATE UNIQUE INDEX PK_PRETA ON PRESTAMO (CODLIBRO, NUMLECTOR, FPRESTA);
CREATE UNIQUE INDEX SYS_C007504 ON LIBRO (CODLIBRO);
CREATE UNIQUE INDEX SYS_C007505 ON LECTOR (NUMLECTOR);

ALTER TABLE ALUMNOS ADD CONSTRAINT ALU_PK_DNI PRIMARY KEY (DNI);
ALTER TABLE ALUMNOS MODIFY DNI VARCHAR(10) NOT NULL;

ALTER TABLE ALUM1213 ADD CONSTRAINT ALUM_PK_DNI PRIMARY KEY (DNI);
ALTER TABLE ALUM1213 MODIFY DNI VARCHAR(10) NOT NULL;
ALTER TABLE ALUM1213 MODIFY NOMBRE VARCHAR(15) NOT NULL;
ALTER TABLE ALUM1213 MODIFY APELLIDOS VARCHAR(20) NOT NULL;
ALTER TABLE ALUM1213 MODIFY CURSO TINYINT NOT NULL;
ALTER TABLE ALUM1213 MODIFY NIVEL VARCHAR(10) NOT NULL;
ALTER TABLE ALUM1213 MODIFY CLASE CHAR(1) NOT NULL;

ALTER TABLE ASIGNATURAS ADD CONSTRAINT ASI_PK_CO PRIMARY KEY (COD);
ALTER TABLE ASIGNATURAS MODIFY COD TINYINT NOT NULL;

ALTER TABLE DEPART ADD CONSTRAINT DEP_PK_DE PRIMARY KEY (DEPT_NO);
ALTER TABLE DEPART MODIFY DEPT_NO TINYINT NOT NULL;
ALTER TABLE EMPLE ADD CONSTRAINT EMP_PK_EM PRIMARY KEY (EMP_NO);
ALTER TABLE EMPLE MODIFY EMP_NO SMALLINT NOT NULL;
ALTER TABLE EMPLE MODIFY DEPT_NO TINYINT NOT NULL;

ALTER TABLE LECTOR ADD PRIMARY KEY (NUMLECTOR);
ALTER TABLE LIBRERIA MODIFY TEMA VARCHAR(15) NOT NULL;
ALTER TABLE LIBRO ADD PRIMARY KEY (CODLIBRO);

ALTER TABLE NOTAS ADD CONSTRAINT NOT_PK_DNICOD PRIMARY KEY (DNI, COD);
ALTER TABLE NOTAS MODIFY DNI VARCHAR(10) NOT NULL;
ALTER TABLE NOTAS MODIFY COD TINYINT NOT NULL;
ALTER TABLE NOTAS_ALUMNOS MODIFY NOMBRE_ALUMNO VARCHAR(25) NOT NULL;

ALTER TABLE PRESTAMO ADD CONSTRAINT PK_PRETA PRIMARY KEY (CODLIBRO, NUMLECTOR, FPRESTA);

/* AQUÍ ESTÁN LAS  CLAVES FORÁNEAS, COMO COMENTARIO PARA QUE NO HAYA ESTAS RESTRICCIONES PARA LOS EJERCICIOS

--------------------------------------------------------
--  Ref Constraints for Table EMPLE
--------------------------------------------------------
  ALTER TABLE EMPLE ADD CONSTRAINT EMP_FK_DP FOREIGN KEY (DEPT_NO) REFERENCES DEPART (DEPT_NO) ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table NOTAS
--------------------------------------------------------
  ALTER TABLE NOTAS ADD CONSTRAINT NOTAS_FK_COD FOREIGN KEY (COD) REFERENCES ASIGNATURAS (COD) ENABLE;
  ALTER TABLE NOTAS ADD CONSTRAINT NOTAS_FK_DN FOREIGN KEY (DNI) REFERENCES ALUMNOS (DNI) ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table PRESTAMO
--------------------------------------------------------
  ALTER TABLE PRESTAMO ADD CONSTRAINT PRE_FK_CO FOREIGN KEY (CODLIBRO) REFERENCES LIBRO (CODLIBRO) ENABLE;
  ALTER TABLE PRESTAMO ADD CONSTRAINT PRE_FK_NU FOREIGN KEY (NUMLECTOR) REFERENCES LECTOR (NUMLECTOR) ENABLE;
*/